name: "Build and test"

on:
  push:
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  name: build-and-test

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: ./.github/workflows/setup

      - name: Generate protobuf files
        run: |
          pnpm generate

      - name: Test
        run: |
          pnpm test

      - name: Lint
        run: |
          pnpm lint

      - name: Format-check
        run: |
          pnpm format-check

      - name: Check dependencies
        run: |
          pnpm depcheck
